// Generated by CoffeeScript 1.7.1
var express, logger, reply;

express = require('express');

logger = require('winston');

reply = function(res, promise) {
  return promise.then(function(data) {
    return res.send(data);
  })["catch"](function(err) {
    logger.error(err.stack || err);
    return res.send(err.code || 500, err);
  });
};

module.exports = function(options) {
  var app;
  app = express();
  app.use(require('compression')());
  return {
    server: app,
    controller: function(method, pattern, handler) {
      logger.info('[httpd] registering controller at %s %s', method.toUpperCase(), pattern);
      return app[method.toLowerCase()](pattern, function(req, res) {
        return reply(res, handler(req));
      });
    },
    start: function() {
      var port;
      port = options.port || 3000;
      return app.listen(port, function() {
        var baseUrl;
        baseUrl = options.baseUrl || ("http://localhost:" + port);
        return logger.info('[httpd] running at port %s', baseUrl);
      });
    }
  };
};
